version: '3.9'

services:
  # postgres:
  #   image: postgres
  #   container_name: postgres
  #   ports:
  #     - 6500:5432
  #   env_file:
  #     - ./.env
  #   volumes:
  #     - postgres:/var/lib/postgresql/data

  test-postgres:
    image: postgres
    container_name: postgres
    ports:
      - 6505:5432
    env_file:
      - ./.env
    volumes:
      - postgres:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  postgres:
